### ISSUE TITLE
Compilation error .

### ISSUE THREAD

**Issue by ADitya024** [apgapg/DotMyStyle_App#2]
While executing command : flutter run.

I am receiving compilation error . 
Please guide how to resolve it.

Error log : 

Compiler message:
lib/widget/home/category_widget.dart:8:7: Error: Type argument 'CategoryWidget' doesn't conform to the bound 'StatefulWidget' of the type variable 'T' on 'State' in the supertype
'State' of class 'State with SingleTickerProviderStateMixin'.
 - 'CategoryWidget' is from 'package:salon/pages/salon_service_page.dart' ('lib/pages/salon_service_page.dart').
 - 'StatefulWidget' is from 'package:flutter/src/widgets/framework.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try changing type arguments so that they conform to the bounds.
class CategoryWidgetState extends State<CategoryWidget>
      ^
../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/widgets/framework.dart:1029:22: Context: This is the type variable whose bound isn't conformed to.
abstract class State<T extends StatefulWidget> with Diagnosticable {
                     ^
lib/widget/home/category_widget.dart:8:7: Error: Type argument 'CategoryWidget' doesn't conform to the bound 'StatefulWidget' of the type variable 'T' on
'SingleTickerProviderStateMixin' in the supertype 'SingleTickerProviderStateMixin' of class 'State with SingleTickerProviderStateMixin'.
 - 'CategoryWidget' is from 'package:salon/pages/salon_service_page.dart' ('lib/pages/salon_service_page.dart').
 - 'StatefulWidget' is from 'package:flutter/src/widgets/framework.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try changing type arguments so that they conform to the bounds.
class CategoryWidgetState extends State<CategoryWidget>
      ^
../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/widgets/ticker_provider.dart:111:38: Context: This is the type variable whose bound isn't conformed to.
mixin SingleTickerProviderStateMixin<T extends StatefulWidget> on State<T> implements TickerProvider {
                                     ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:461:24: Error: The method
'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_provider.dart:574:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^

Compiler message:
lib/widget/home/category_widget.dart:8:7: Error: Type argument 'CategoryWidget' doesn't conform to the bound 'StatefulWidget' of the type variable 'T' on 'State' in the supertype 'Stat
e' of class 'State with SingleTickerProviderStateMixin'.
 - 'CategoryWidget' is from 'package:salon/pages/salon_service_page.dart' ('lib/pages/salon_service_page.dart').
 - 'StatefulWidget' is from 'package:flutter/src/widgets/framework.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try changing type arguments so that they conform to the bounds.
class CategoryWidgetState extends State<CategoryWidget>
      ^
../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/widgets/framework.dart:1029:22: Context: This is the type variable whose bound isn't conformed to.
abstract class State<T extends StatefulWidget> with Diagnosticable {
                     ^
lib/widget/home/category_widget.dart:8:7: Error: Type argument 'CategoryWidget' doesn't conform to the bound 'StatefulWidget' of the type variable 'T' on 'SingleTickerProviderStateMixi
n' in the supertype 'SingleTickerProviderStateMixin' of class 'State with SingleTickerProviderStateMixin'.
 - 'CategoryWidget' is from 'package:salon/pages/salon_service_page.dart' ('lib/pages/salon_service_page.dart').
 - 'StatefulWidget' is from 'package:flutter/src/widgets/framework.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try changing type arguments so that they conform to the bounds.
class CategoryWidgetState extends State<CategoryWidget>
      ^
../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/widgets/ticker_provider.dart:111:38: Context: This is the type variable whose bound isn't conformed to.
mixin SingleTickerProviderStateMixin<T extends StatefulWidget> on State<T> implements TickerProvider {
                                     ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:461:24: Error: The method 'CachedNetworkImageProvid
er.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_provider.dart:574:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:199:38: Error: The argument type 'void
Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
      oldImageStream?.removeListener(_handleImageChanged);
                                     ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:200:32: Error: The argument type 'void
Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
      _imageStream.addListener(_handleImageChanged);
                               ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:210:34: Error: The argument type 'void
Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
    _imageStream?.removeListener(_handleImageChanged);
                                 ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:465:31: Error: The argument type 'Null
Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
        informationCollector: (StringBuffer information) {
                              ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:199:38: Error: The argument type 'void Function(Ima
geInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
      oldImageStream?.removeListener(_handleImageChanged);
                                     ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:200:32: Error: The argument type 'void Function(Ima
geInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
      _imageStream.addListener(_handleImageChanged);
                               ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:210:34: Error: The argument type 'void Function(Ima
geInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
    _imageStream?.removeListener(_handleImageChanged);
                                 ^
../flutter_windows_1.17.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:465:31: Error: The argument type 'Null Function(Str
ingBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('../flutter_windows_1.17.1-stable/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
        informationCollector: (StringBuffer information) {
                              ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\workspace\projects\flutter_windows_1.17.1-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 885

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\workspace\projects\flutter_windows_1.17.1-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        70.5s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by apgapg** [comment]
I think the packages got out of date. Let me update the repo.

**Comment by apgapg** [comment]
I have updated the repo. 

Run 
```git pull```

**Comment by ADitya024** [comment]
Okay .
Thanks Ayush.
